image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - npm
  - esbuild
  - zola
  - hut
environment:
  repo: ch-site
  site: curtis3389.srht.site
tasks:
  - build: |
      cd $repo
      npm install
      esbuild ./content/blog/mandelbrot/main.js --bundle --minify --sourcemap --outfile=content/blog/mandelbrot/bundle.js
      zola build
  - package: |
      cd $repo
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
